React capstone project - Metrics webapp
HENRYKC24/covid19-info-finder pull request #7
Opened 2021-10-15 15:27 UTC by HENRYKC24

### In this pull request, I did the following:point_down:
1. When the page loads, the web app shows the list of categories that could be filtered out by country name.
2. I display some numeric values per country that come from an API in the app.
3. When the user clicks (or taps) on a country, the application navigates to the country details page.
4. On the details page, the web app retrieves data from the API to show detailed data in the country.
5. When the user clicks on the "Back" button (<), the user navigates to the home page.
6. I created unit tests for pure functions in your Redux code.
7. I created integration tests for your application using the React Testing Library.
8. I deployed the app.
9. I recorded a 5 minutes video and described the app therein.

2021-10-15 17:44 UTC, oloomoses requested changes
Hi @HENRYKC24, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 17:44 UTC, oloomoses commented on README.md
> +- A special thanks goes to all my peers at Microverse for being ther for me.
- [ ] Kindly give credit to Nelson Sakwa, Creator of the original design as per the project requirements.

2021-10-15 17:44 UTC, oloomoses commented on src/redux/configureStore.js
> +
- [ ] Please do not log redux data on the browser console as it may cause site security issues. Kindly clear the logged data displayed on the browser console.

2021-10-15 17:44 UTC, oloomoses commented on src/tests/Footer.test.js
> +import renderer from 'react-test-renderer';
- [ ] Kindly delete the commented piece of code because they make your work look messy.

2021-10-15 17:44 UTC, oloomoses commented on src/tests/TableRow.test.js
> +import renderer from 'react-test-renderer';
- [ ] Kindly delete the commented piece of code because they make your work look messy.

2021-10-15 18:17 UTC, HENRYKC24 commented on README.md
> +- A special thanks goes to all my peers at Microverse for being ther for me.
Thank you very much. Done!

2021-10-15 18:18 UTC, HENRYKC24 commented on src/tests/TableRow.test.js
> +import renderer from 'react-test-renderer';
Sure. Thanks for your expensive time once agan.

2021-10-16 02:35 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @HENRYKC24,

Good job on implementing the suggested changes. Well Done.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-16 10:14 UTC, merged

2021-10-16 10:15 UTC, HENRYKC24 commented
Thank you.